#Bootstrap 3
TABLE_CONDENSED = ".table-condensed"
CONTROL_LABEL = ".control-label"
RADIO = ".radio"
RADIO_INLINE = ".radio-inline"
CHECKBOX = ".checkbox"
CHECKBOX_INLINE = ".checkbox-inline"
INPUT_LG = ".input-lg"
INPUT_SM = ".input-sm"
HELP_BLOCK = ".help-block"
BUTTON_DEFAULT = ".btn-default"
IMAGE_RESPONSIVE = ".img-responsive"
CENTER_BLOCK = ".center-block"
DIVIDER = ".divider"
LIST_GROUP_ITEM = ".list-group-item"
BREADCUM = ".breadcrumb"
ITEM = ".item"

#Bootstrap4
table_condensed = ".table-sm"
control_label = ".col-form-label"
radio = ".form-check"
radio_inline = ".form-check-label"
checkbox = ".form-check-input"
checkbox_inline = ".form-check-inline"
input_lg = ".form-control-lg"
input_sm = ".form-control-sm"
help_block = ".form-text"
button_default = ".btn-secondary"
image_responsive = ".img-fluid"
center_block = ".m-x-auto"
divider = ".dropdown-divider"
list_group_item = ".list-group-item-action"
breadcum = ".breadcrumb-item"
item = ".carousel-item"
